cmake_minimum_required(VERSION 3.13)
include(pico_sdk_import.cmake)
project(earthquake-sensor C CXX ASM)
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)
pico_sdk_init()
add_executable(main main.c ili9341.c)
add_executable(test_ili9341 test_ili9341.c ili9341.c)
target_link_libraries(main pico_stdlib hardware_spi hardware_i2c hardware_uart hardware_rtc)
target_link_libraries(test_ili9341 pico_stdlib hardware_spi)
pico_add_extra_outputs(main)
pico_add_extra_outputs(test_ili9341)